# Generated by Django 4.0.6 on 2022-07-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tweet-images'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('reply_img', models.ImageField(blank=True, null=True, upload_to='uploads/tweet-images/replies')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tweets.tweet')),
            ],
        ),
    ]
